# Author: Sarah Harrington
# E-mail: sharrin3@nd.edu
#
# This is the Makefile for the Lecture 8 Example.

# gcc is for the compiler for C
CC := gcc

# CFLAGS are the compiler flags for when we compile C code in this course
FLAGS := -O2 -g -Wall -Wextra -Wconversion -Werror # for optimization and ability to analyse on machine level

CFLAGS := -std=c2x $(FLAGS)

# Create the Pallel Lib Library
parallel_lib.o: parallel_lib.C
	$(CC) $(CFLAGS) -c parallel_lib.c

# Create the Pallel Run


# Parallel Program Objects

#Executables


# Executable Names


# Make all


# Make clean

